### ISSUE TITLE
嗯。。。能加个 切换 按钮啥的么？毕竟有时候需要临时全局代理的话。。。

### ISSUE THREAD

**Issue by laincat** [jc3213/SimpleProxy#3]
虽然可以临时改一下规则。只是为了临时用一下比较麻烦。。。

**Comment by jc3213** [comment]
这个当时发到群里也有人提过，因为SimpleProxy没有完全接管火狐的代理设置，最后他们选择用鼠标手势去解决了。。。。

再就是，最开始的版本本来是有工具栏图标的，也是被人说没必要，简单就好。因此这个功能就是要加也是加在about:addons扩展管理界面，我反而觉得加在哪里比起手动打开设置也没方便多少。。。也就没加。

推荐试试鼠标手势修改 network.proxy.type 会比较好。也可以做addMenuPlus.us.js添加一个右键菜单切换这个参数就行了。。。会比弄得太复杂简单得多。

**Comment by jc3213** [comment]
这里给个addMenuPlus的解决方案吧。我不是太知道Moz有什么别的API可以把用户设置单独保存出来。addon-sdk的话倒是可以用simple-storage来操作。

    {
        label: "切换全局/个人代理设置",
        class: "proxy-switch",
        oncommand: function(){
           var prefService = Cc['@mozilla.org/preferences-service;1'].getService(Ci.nsIPrefService).QueryInterface(Ci.nsIPrefBranch);
           var proxyType = prefService.getIntPref('network.proxy.type');
           if (proxyType != 2) {
             prefService.setIntPref('network.proxy.type', 2)
           } else {
             prefService.setIntPref('network.proxy.type', 1)  //请自己填写自己要的值， 1是手动代理，5是系统代理，4是自动检测，2是使用PAC，0是无代理
           }
        }
    },

**Comment by laincat** [comment]
好的，感谢。

**Comment by jc3213** [comment]
oncommand部分的代码也可以用于鼠标手势，就是看你怎么选择了，如果你用起来没什么问题的话，我考虑关闭这个issue了。

**Comment by laincat** [comment]
虽然还没尝试大大的方法。不过既然有解决方法了。谢谢的说。关了吧。:)
